### ISSUE TITLE
启动时出现报错，并且无法正常使用智能TAB、智能F1等功能

### ISSUE THREAD

**Issue by yybbwc** [telppa/SciTE4AutoHotkey-Plus#1]
![QQ图片20201101193743](https://user-images.githubusercontent.com/40225162/97801869-bef13a00-1c7a-11eb-869a-57f6d895b63c.png)
![QQ图片20201101193756](https://user-images.githubusercontent.com/40225162/97801873-c3b5ee00-1c7a-11eb-80a6-313feefb0106.png)
![QQ图片20201101194533](https://user-images.githubusercontent.com/40225162/97801885-d9c3ae80-1c7a-11eb-9398-8b7cfa85c894.png)

**Comment by telppa** [comment]
看不到图。通常你可以试试管理员权限运行一次，然后不用管理员权限运行一次。

**Comment by wujun001** [comment]
相同问题

环境:
- win10家庭中文版，版本1909
- SciTE4AutoHotkey-Plus_v2021.01.03

描述：
普通用户启动正常，管理员权限启动时autorun.ahk报错，此时一些中文帮助失效

**Comment by telppa** [comment]
> 相同问题
> 
> 环境:
> 
> * win10家庭中文版，版本1909，64位
> * SciTE4AutoHotkey-Plus_v2021.01.03
> 
> 描述：
> 描述：
> 
> * 普通用户启动正常，管理员权限启动时autorun.ahk报错，此时一些中文帮助失效
> * 代码11行和212行的ComObjActive
> 
> @telppa

如果普通权限运行正常 就用普通权限运行
你没有用绿色版ahk之类的东西吧
