### ISSUE TITLE
Toolbar错误

### ISSUE THREAD

**Issue by Sherlock2435** [telppa/SciTE4AutoHotkey-Plus#10]
修改ahk文件打开方式为 SciTE4AutoHotkey-Plus后Toolbar消失,报错内容如下:
<img width="334" alt="Snipaste_2021-04-06_01-33-06" src="https://user-images.githubusercontent.com/35016940/113606736-fbd2ba00-967a-11eb-9556-0152bc17d05a.png">

环境:
- Windows10 专业版,64位

- SciTE4AutoHotkey-Plus_v2021.03.28

**Comment by telppa** [comment]
账户权限有问题，如果你用的是administrator，那就重新建一个管理员账户。
另外，如果有360，删了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/SciTE4AutoHotkey-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 凌晨1:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/SciTE4AutoHotkey-Plus] Toolbar错误 (#10)





 
报错内容如下:
 
 
环境:
  
 
Windows10 专业版,64位
 
 
 
SciTE4AutoHotkey-Plis_v2021.03.28

**Comment by godefy** [comment]
我也遇到这个问题,一打开SciTE4AutoHotkey程序就会报这个错误。
能否说下这个错误引起的具体原因?

**Comment by godefy** [comment]
尝试了一下以管理员权限运行,就不弹这个弹窗了,但是会弹其它报错。具体我单发一下。
