### ISSUE TITLE
打开SciTE4AutoHotkey时的报错

### ISSUE THREAD

**Issue by godefy** [telppa/SciTE4AutoHotkey-Plus#11]
以管理员身份运行
打开时会报两个错误:
![image](https://user-images.githubusercontent.com/19462833/114118272-1aef7700-991b-11eb-9c6f-b58c76e2dfd8.png)
![image](https://user-images.githubusercontent.com/19462833/114118279-1dea6780-991b-11eb-9913-226f14b0faad.png)
确认ahk所在路径无中文,并且AutoHotkey_CN.chm帮助文件存在

**Comment by godefy** [comment]
补充:
不以管理员运行,就不会报这个错误。

**Comment by telppa** [comment]
尝试，新建一个管理员账户（不能是administrator），然后在这个账户下，第一次用管理员权限运行，会报错，点继续，然后关了，然后正常运行，应该就正常了。


第二个帮助不在的问题，截图帮助文件所在目录（把其它文件也截里面，尽量全面点）。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/SciTE4AutoHotkey-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 上午10:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/SciTE4AutoHotkey-Plus] 打开SciTE4AutoHotkey时的报错 (#11)





 
以管理员身份运行
 打开时会报两个错误:
 
 
 确认ahk所在路径无中文,并且AutoHotkey_CN.chm帮助文件存在
