### ISSUE TITLE
请问缩略词ctrl+b功能具体是在哪里进行定义和维护?

### ISSUE THREAD

**Issue by godefy** [telppa/SciTE4AutoHotkey-Plus#12]
请问缩略词ctrl+b 功能具体是在哪里进行定义和维护?
![image](https://user-images.githubusercontent.com/19462833/114135718-3d45bc80-993c-11eb-9993-207fdb7b8f94.png)

**Comment by telppa** [comment]
user\AhkAbbrevs.properties




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/SciTE4AutoHotkey-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午2:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/SciTE4AutoHotkey-Plus] 请问缩略词ctrl+b功能具体是在哪里进行定义和维护? (#12)





 
请问缩略词ctrl+b 功能具体是在哪里进行定义和维护?

**Comment by godefy** [comment]
秒回复啊,太厉害啦!
