### ISSUE TITLE
代码格式化功能,对注释会进行一个TAB缩进,是正常的吗?

### ISSUE THREAD

**Issue by godefy** [telppa/SciTE4AutoHotkey-Plus#13]
我使用代码格式化功能后,发现有些使用";"打的注释前面增加了一个制表符,正常是正常的吗?
但还发现并不是所有都会这样,也没发现什么规律。不知道是不是bug。

**Comment by godefy** [comment]
有的没缩进
![image](https://user-images.githubusercontent.com/19462833/114138277-fbb71080-993f-11eb-8893-e9dabb41a252.png)
有的被缩进了
![image](https://user-images.githubusercontent.com/19462833/114138352-15585800-9940-11eb-98d1-2021ab337326.png)

**Comment by telppa** [comment]
发图看看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [telppa/SciTE4AutoHotkey-Plus] 代码格式化功能,对注释会进行一个TAB缩进,是正常的吗? (#13)





 
我使用代码格式化功能后,发现有些使用";"打的注释前面增加了一个制表符,正常是正常的吗?
 但还发现并不是所有都会这样,也没发现什么规律。不知道是不是bug。

**Comment by godefy** [comment]
还有就是,代码的缩进好像有些bug。
就是有的地方会莫名其妙的产生缩进,比如:
![image](https://user-images.githubusercontent.com/19462833/114138541-5ea8a780-9940-11eb-953c-f27a011ab2f4.png)

**Comment by telppa** [comment]
不正常。因为v1的代码解析实在太复杂了，加上我后期写代码已经完全不需要再单独格式化一遍了，加上代码格式化工具太老了，所以我只修复了它的恶性bug，并且支持了后期的一些新语法，但不保证完美的效果。一般对新人还是比较有用的。有些特别多热键的代码或者特别多if的代码，是可能缩进错误的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/SciTE4AutoHotkey-Plus] 代码格式化功能,对注释会进行一个TAB缩进,是正常的吗? (#13)





 
有的没缩进
 
 有的被缩进了

**Comment by godefy** [comment]
请问你用ahk是用的v1.1还是v2呢?

**Comment by telppa** [comment]
1.1&nbsp;
你要不要加个群 717947647，这里面还有很多小伙伴（ahk的不是编辑器的）， 有问题都可以讨论。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/SciTE4AutoHotkey-Plus] 代码格式化功能,对注释会进行一个TAB缩进,是正常的吗? (#13)





 
请问你用ahk是用的v1.1还是v2呢?

**Comment by godefy** [comment]
> 1.1&nbsp; 你要不要加个群 717947647，这里面还有很多小伙伴（ahk的不是编辑器的）， 有问题都可以讨论。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月9日(星期五) 下午2:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [telppa/SciTE4AutoHotkey-Plus] 代码格式化功能,对注释会进行一个TAB缩进,是正常的吗? (#13) 请问你用ahk是用的v1.1还是v2呢? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的

**Comment by godefy** [comment]
还有个问题就是 这个代码格式化工具是不是只支持全局格式化,我选中了部分代码,运行后发现好像也是全局进行了格式化。

**Comment by telppa** [comment]
可以部分格式化。如果失败，就ctrl+z，然后再次尝试部分格式化。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/SciTE4AutoHotkey-Plus] 代码格式化功能,对注释会进行一个TAB缩进,是正常的吗? (#13)





 
还有个问题就是 这个代码格式化工具是不是只支持全局格式化,我选中了部分代码,运行后发现好像也是全局进行了格式化。

**Comment by godefy** [comment]
> 可以部分格式化。如果失败，就ctrl+z，然后再次尝试部分格式化。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月9日(星期五) 下午2:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [telppa/SciTE4AutoHotkey-Plus] 代码格式化功能,对注释会进行一个TAB缩进,是正常的吗? (#13) 还有个问题就是 这个代码格式化工具是不是只支持全局格式化,我选中了部分代码,运行后发现好像也是全局进行了格式化。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的 谢谢
