### ISSUE TITLE
F1快捷帮助打开chm后的显示问题

### ISSUE THREAD

**Issue by godefy** [telppa/SciTE4AutoHotkey-Plus#15]
常规方式打开一个文件或应用的窗口，通常是会记忆位置的。
而我在SciTE中使用F1打开帮助文件，默认的窗口总会被设置成一个固定的（且不是动态布局）。
因为我习惯将系统任务栏设置到屏幕顶部，这样每次那个固定布局顶部都会被我的屏幕顶部遮挡住需要手动去调整一下大小。
想知道有没有什么办法能让这个F1调用出的帮助能记忆位置 或者是 布局是动态（类似快捷键win+right效果）而不是强制固定。

目前每次我打开都会变成这样:

![image](https://user-images.githubusercontent.com/19462833/114256476-07f8a780-99ec-11eb-975a-22c2b41fe226.png)

**Comment by telppa** [comment]
&nbsp; if (重定位帮助文件显示位置)
&nbsp; {
&nbsp; &nbsp; SysGet, WorkArea, MonitorWorkArea, 1&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;; 获取工作区尺寸，即不含任务栏的屏幕尺寸。
&nbsp; &nbsp; DPIScale:=A_ScreenDPI/96
&nbsp; &nbsp; W:=(WorkAreaRight-WorkAreaLeft)//2
&nbsp; &nbsp; X:=WorkAreaLeft+W+(-1+8)*DPIScale
&nbsp; &nbsp; Y:=WorkAreaTop
&nbsp; &nbsp; H:=WorkAreaBottom-Y+(-1+8)*DPIScale
&nbsp; &nbsp; WinMove, ahk_exe keyhh.exe,, X, Y, W, H&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ; 显示在屏幕右侧并占屏幕一半尺寸。
&nbsp; &nbsp; 重定位帮助文件显示位置:=0
&nbsp; }



没想过有人任务栏放其它位置。用以上代码替换&nbsp;SciTE\user\Autorun.ahk 中的对应内容即可，现在上下左右任务栏都能正常工作了。


另外，你有时候可能忘了，ahk本身就最擅长热键处理问题的呀。我没解决问题前，其实你可以用 winwait 然后send,#right 解决问题的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/SciTE4AutoHotkey-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月10日(星期六) 中午11:01
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/SciTE4AutoHotkey-Plus] F1快捷帮助打开chm后的显示问题 (#15)





 
常规方式打开一个文件或应用的窗口，通常是会记忆位置的。
 而我在SciTE中使用F1打开帮助文件，默认的窗口总会被设置成一个固定的（且不是动态布局）。
 因为我习惯将系统任务栏设置到屏幕顶部，这样每次那个固定布局顶部都会被我的屏幕顶部遮挡住需要手动去调整一下大小。
 想知道有没有什么办法能让这个F1调用出的帮助能记忆位置 或者是 布局是动态（类似快捷键win+right效果）而不是强制固定。
 
目前每次我打开都会变成这样:

**Comment by godefy** [comment]
好的 非常感谢
上午我找到这块了 就把重置位置这部分给屏蔽了
