### ISSUE TITLE
打开SciTE时Toolbar.ahk报错

### ISSUE THREAD

**Issue by godefy** [telppa/SciTE4AutoHotkey-Plus#16]
![image](https://user-images.githubusercontent.com/19462833/114293641-7b70e680-9aca-11eb-95d6-f635b404052d.png)
之前用着正常，不知道什么原因就突然一直报这个错误，怎么选都是这样。然后上面的插件按钮也显示不出来了。

**Comment by telppa** [comment]
前一个toolbar进程被冻死了，关不了。任务管理器里手动杀进程试试，或者更简单一点，重启或注销。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/SciTE4AutoHotkey-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 中午1:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/SciTE4AutoHotkey-Plus] 打开SciTE时Toolbar.ahk报错 (#16)





 

 之前用着正常，不知道什么原因就突然一直报这个错误，怎么选都是这样。然后上面的插件按钮也显示不出来了。

**Comment by godefy** [comment]
好的 谢谢
