### ISSUE TITLE
用了很多年SciTE4AutoHotkey，缺一个书签列表视图

### ISSUE THREAD

**Issue by hui-Zz** [telppa/SciTE4AutoHotkey-Plus#17]
SciTE因为缺一个书签列表视图 和 多窗口并列，所以想方便改大AHK只能用VSCode

但是Debug模式目前还是SciTE最好，断点运行还是得用回SciTE

**Comment by telppa** [comment]
发点图我看看都长啥样的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/SciTE4AutoHotkey-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午5:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/SciTE4AutoHotkey-Plus] 用了很多年SciTE4AutoHotkey，缺一个书签列表视图 (#17)





 
SciTE因为缺一个书签列表视图 和 多窗口并列，所以想方便改大AHK只能用VSCode
 
但是Debug模式目前还是SciTE最好，断点运行还是得用回SciTE

**Comment by hui-Zz** [comment]
![RunAnyVSCode.jpg](https://i.loli.net/2021/05/12/JoOlubfM2vcXpj9.jpg)
上面是我在用的VSCode编辑AHK视图
主要是左侧有丰富的功能栏，自带：文件目录树、大纲，插件：书签列表、本地修改历史、Git时间线
缺点是Debug模式功能残缺，对象值都看不了

- 目前SciTE的大纲需要中键唤出不能固定
- 有书签功能，但是没有视图显示，只能不断按F2切换书签，是非常麻烦的！
- 不借助第三方目前不能双开SciTE，所以即使没有VSCode那样程序内拆分编辑视图，连多个Windows窗口也没办法做到
这样对于多屏幕的开发者开发效率会很低下

**Comment by telppa** [comment]
有道理。不过我觉得，从vs下手比较容易解决你的需求。群里不是有大佬开发debug插件的吗？你去找大佬反馈下，说不定功能就有了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/SciTE4AutoHotkey-Plus] 用了很多年SciTE4AutoHotkey，缺一个书签列表视图 (#17)





 

 上面是我在用的VSCode编辑AHK视图
 主要是左侧有丰富的功能栏，自带：文件目录树、大纲，插件：书签列表、本地修改历史、Git时间线
 缺点是Debug模式功能残缺，对象值都看不了
  
目前SciTE的大纲需要中键唤出不能固定
 
有书签功能，但是没有视图显示，只能不断按F2切换书签，是非常麻烦的！
 
不借助第三方目前不能双开SciTE，所以即使没有VSCode那样程序内拆分编辑视图，连多个Windows窗口也没办法做到
 这样对于多屏幕的开发者开发效率会很低下

**Comment by hui-Zz** [comment]
从开发复杂度来讲，开发一个新debug插件各种成本远远高于加一个视图窗口
SciTE功能都有，只是需要有一个把书签显示出来的窗口而已，窗口双开也可以自己想办法

**Comment by telppa** [comment]
不是，咱群里不是有大佬开发了ahk的debug插件吗?而且他们比我更熟vs，说不定其实vs本来就有更好的debug插件或者大佬直接能帮你加上查看对象值的功能。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/SciTE4AutoHotkey-Plus] 用了很多年SciTE4AutoHotkey，缺一个书签列表视图 (#17)





 
从开发复杂度来讲，开发一个新debug插件各种成本远远高于加一个视图窗口
 SciTE功能都有，只是需要有一个把书签显示出来的窗口而已，窗口双开也可以自己想办法

**Comment by hui-Zz** [comment]
好的多谢，我之前试了几款插件都有一些问题，
刚刚又发现了几款没用过的插件，我再试试
