### ISSUE TITLE
建议2条

### ISSUE THREAD

**Issue by cnkiller** [telppa/SciTE4AutoHotkey-Plus#18]
1、增加自动括号完成。
这个比较简单，我是按照https://www.autoahk.com/archives/28793这个添加的，希望可以添加

2、增加一个帮助菜单
增加一个帮助菜单，可以跳转到帮助的html，另外，帮助的html建议增加上相关的网址作者，方便快速到这里

**Comment by telppa** [comment]
功能1其实以前有过，忘了什么原因取消了，估计就是不好用吧。

功能2是指对着关键词按F1的话，这是有的。不是的话可以描述再详细点。

**Comment by cnkiller** [comment]
功能2是工具栏有一个按键可以跳转到 技巧说明.html ，另外技巧说明.html 目前只有使用提示，希望可以有个跳转到 https://github.com/telppa/SciTE4AutoHotkey-Plus 的连接，方便快速跳转

**Comment by telppa** [comment]
好的，我考虑下。
