### ISSUE TITLE
Auto-GUI 不支持高分屏

### ISSUE THREAD

**Issue by cnkiller** [telppa/SciTE4AutoHotkey-Plus#19]
我是1080的笔记本，调整了120%的缩放。
打开Auto-GUI，提示如下：
Auto-GUI has not been adapted to High-DPI display scaling.

The program will exit.
是否考虑增加其他的GUI工具？

**Comment by telppa** [comment]
最新版我去掉了这个限制，不过没有推送更新，你自己下载一下，替换原文件。

https://github.com/telppa/SciTE4AutoHotkey-Plus/tree/master/SciTE/tools/Auto-GUI
