### ISSUE TITLE
建议修改

### ISSUE THREAD

**Issue by woaidianqian** [telppa/SciTE4AutoHotkey-Plus#22]
目前双击scite.exe的时候，程序默认调用系统安装的ahk程序打开自动更新.ahk;
应当先检测系统是否安装了ahk，如果没有安装则应当检测与SciTE位于相同目录中的相对路径的autohotkey.exe程序
![image](https://user-images.githubusercontent.com/10897660/148641282-31868dd1-a780-4635-b4b7-fb5c8ee1cd79.png)
建议直接关联相对路径中的ahk程序。

**Comment by telppa** [comment]
这样做的必要性是什么呢？

**Comment by woaidianqian** [comment]
> 

我是想做一个不需要管理员权限的便携版是最好的，开箱即用，不依赖系统的ahk，不过我可以根据你这个autorun.ahk文件进行修改，改成不检测更新以及安装字体。
