### ISSUE TITLE
纯粹反馈,强烈支持!

### ISSUE THREAD

**Issue by Lancename** [telppa/SciTE4AutoHotkey-Plus#23]
最近也迷上了这个玩意,爆肝了好几天.   
困于很多现有人机交互方式跟傻瓜一样.到处找插件.
终于发现可以自己动手解决多数问题了.

**Comment by telppa** [comment]
建议从 scite交互示例.ahk 入手。版本号 2022.04.26 及之后的版本，大幅更新了交互示例。
