### ISSUE TITLE
[功能请求]标题栏仅显示文件名

### ISSUE THREAD

**Issue by photkey** [telppa/SciTE4AutoHotkey-Plus#24]
1、可选功能：标题栏 仅显示文件名，看起来更舒服一点，尤其是从任务栏看的时候；

![image](https://user-images.githubusercontent.com/60434581/160074926-032d0154-f317-4c95-8015-7319bb58334c.png)
2、这些选项改变后，建议可以保存在配置中。比方我习惯显示空白字符，每次编辑脚本的时候，都要重新设置一下，有点麻烦哦。

**Comment by telppa** [comment]
设置里都有，SciTEGlobal.properties 里去找，然后写到 SciTEUser.properties 里

**Comment by photkey** [comment]
谢谢，设置都找到了。
再问下，可不可以只显示空格，不显示Tab？或者，这个是应该从设置里面修改，还是从样式就（style）里面修改？
