### ISSUE TITLE
Lua: error occurred while loading startup script

### ISSUE THREAD

**Issue by z775729168** [telppa/SciTE4AutoHotkey-Plus#25]
```
cannot open D:\SCOOP\apps\autohotkey\1.1.33.10\SciTE/extensions/自动完成增强版.lua: No such file or directory
>Lua: error occurred while loading startup script
```

![image](https://user-images.githubusercontent.com/24876796/160424446-2e752a6b-e17e-4324-9b6b-63d07f7fd1f0.png)

win10 英文，编码为unicode。
如果使用Locale Emulator转为GBK编码，就无报错。

**Comment by telppa** [comment]
精力有限，且正如此项目的定位——中文用户的IDE，所以一般不考虑英文的兼容。

所有地方文件名改成英文应该可以解决这个问题。
