### ISSUE TITLE
编辑器路径错误

### ISSUE THREAD

**Issue by photkey** [telppa/SciTE4AutoHotkey-Plus#27]
![image](https://user-images.githubusercontent.com/60434581/166105991-a5b16832-6f8e-42d1-9c15-ae842fe146fb.png)
Windows11
AutoHotkey_1.1.33.11
autohotkey反复卸载安装好几次了，一直是提示“编辑器路径错误”，请问下这个到底是什么原因导致的？

**Comment by telppa** [comment]
把ahk装d盘，或者没有管理员权限吧。
