### ISSUE TITLE
 SciTE4AutoHotkey-Plus 最新版本 v2022.05.25  ,无法显示 :*:

### ISSUE THREAD

**Issue by muyuan11** [telppa/SciTE4AutoHotkey-Plus#28]
不论是ahk文件中代码包含:*:，还是粘贴:*: ,SciTE4AutoHotkey会自动跳出

只要我在 ahk代码中使用  :*:   ,SciTE4AutoHotkey 就会自动跳出， 原因未知

-----------

 SciTE4AutoHotkey-Plus   v2022.05.25

**Comment by telppa** [comment]
![QQ截图20220705121228](https://user-images.githubusercontent.com/68984587/177247982-7f5aeffe-81dc-4bef-b9a1-7e81766aa400.png)
显示正常
