### ISSUE TITLE
六年了，这么个简单错误一直不解决？

### ISSUE THREAD

**Issue by linlance** [telppa/SciTE4AutoHotkey-Plus#29]
https://zhuanlan.zhihu.com/p/19827020?refer=autohotkey

2017-02-01
[SciTE4AHK 小改进整合中文版](http://link.zhihu.com/?target=http%3A//ahk8.com/thread-4994.html) 无法运行，双击运行提示如下：

Error while launching
""C:\users\[http://adang](http://link.zhihu.com/?target=http%3A//adang)@qq.com\AppData\Local\AutoHotkey_cn\SciTE\..\AutoHotkeyU32.exe" With Params:
""C:\users\[http://adang](http://link.zhihu.com/?target=http%3A//adang)@qq.com\AppData\Local\AutoHotkey_cn\SciTE\toolbar\Toolbar.ahk"
1378572 1 313988 ．
系统找不到指 定的 文件 。

2022-07-15
能不能绿色一点，英文的就直接可以运行，这个所谓整合版，系统找不到制定的文件错误好多年了，也不解决。。
不是每个人都想安装的。

**Comment by telppa** [comment]
6年了这么简单的问题都不会自己解决？

安装.ahk 就是为了尽量解决不同机器可能的问题而写的，要不是有这个步骤，你目录可能出错，权限可能出错，运行代码的ahk还是很低版本的，并且跟主ahk版本还不一致，出错查都查不出原因。

不是每个人都想搞无意义的绿色，更不是每个人连 安装.ahk  代码都不看就来喷的。
