### ISSUE TITLE
ahk.lua open include

### ISSUE THREAD

**Issue by liyuanmeng** [telppa/SciTE4AutoHotkey-Plus#34]
希望添加成如下 554行
	elseif FileExists(IncFile) then
		scite.Open(IncFile)
	elseif FileExists(props['LuaFileDir'].."\\"..IncFile) then
		scite.Open(props['LuaFileDir'].."\\"..IncFile)
	else
		print("File not found! Specified: '"..IncFile.."'")
	end
解决非当前路径打开的文件定位不了的问题

**Comment by telppa** [comment]
给个例子，修复了哪种include的情况。

**Comment by liyuanmeng** [comment]
汗，估计是用以前版本有这种问题。刚刚测试了几个，发现没有问题了，只是在utf8编码下，如果用中文的incude会报个错，要打开的是个乱码的文件。
还有一个问题，我以前修改过程序的源代码，为了实现中文莫名奇妙变色的问题。如果有需要可以把代码发给你，不过新版本的现在出来了，可能也不需要这些老版本的了。
