### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by xspoco** [telppa/SciTE4AutoHotkey-Plus#39]
![image](https://user-images.githubusercontent.com/19290455/230666822-5be90cd8-7b99-4803-81c8-dac8fddf82e2.png)
---------------------------
安装SciTE.ahk
---------------------------
Error at line 123.

Line Text: switch, RunAsAdmin
Error: This line does not contain a recognized action.

The program will exit.
---------------------------
确定   
---------------------------

系统是windows10

**Comment by telppa** [comment]
ahk版本太低
