### ISSUE TITLE
请问能否做成编写版本

### ISSUE THREAD

**Issue by woaidianqian** [telppa/SciTE4AutoHotkey-Plus#4]
你好，请问能做成便携版本的吗，由于工作用的电脑没有管理员权限，直接运行安装程序会提示失败，文件复制过去也会提示失败，要是能做成编写版的那就实在是太好了

**Comment by telppa** [comment]
安装程序基本只做了2件事。
1是把scite目录复制到autohotkey.exe所在位置。
2是安装雅黑等宽字体。
所以你可以尝试手动完成这两步，一样运行。如果字体实在没法安装，可能还需要屏蔽相关检测代码（运行scite.exe时会弹框的）。
