### ISSUE TITLE
点击 运行(F5)时 会产生多个实例

### ISSUE THREAD

**Issue by wysnxzm** [telppa/SciTE4AutoHotkey-Plus#41]
已使用#SingleInstance Force进行单个实例设置,但是 运行 还是会产生一个额外的实例使用 快速运行 则不会

**Comment by wysnxzm** [comment]
貌似问题是无法将旧实例结束导致的,尝试全局关闭管理员控制问题依旧产生

**Comment by telppa** [comment]
这跟scite本身有些关系，不是很好修复，建议你按f5，这样就只有一个实例。f6会产生多个实例
