### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by ruchid123123** [telppa/SciTE4AutoHotkey-Plus#44]
![image](https://github.com/telppa/SciTE4AutoHotkey-Plus/assets/35169879/723e3906-260a-44d5-8c90-98f81b9f1f6c)

**Comment by ruchid123123** [comment]
在C盘根目录下使用管理员运行，无法安装。

**Comment by ruchid123123** [comment]
找到办法了，此软件和ahk的安装路径有关系，要把ahk的路径调整到根目录下。

**Comment by 482787082** [comment]
> 找到办法了，此软件和ahk的安装路径有关系，假设ahk的路径调整到根目录下。

但好像AHK只能安装在Program这样的目录下，你看我重新安装AHK的提示：
Enabling Ul Access will not be possible because the installationdirectory is not a sub-directory of Program Files. Without Ul Access.non-elevated scripts cannot interact with windows of elevatedprograms.

**Comment by 482787082** [comment]
> 找到办法了，此软件和ahk的安装路径有关系，假设ahk的路径调整到根目录下。

然后这软件又说AHK不能安装在Program Files
好矛盾啊

**Comment by telppa** [comment]
> > 找到办法了，此软件和ahk的安装路径有关系，假设ahk的路径调整到根目录下。
> 
> 然后这软件又说AHK不能安装在Program Files 好矛盾啊

别装program files，需要权限的脚本用管理员方式运行。
