### ISSUE TITLE
快捷方式拖入窗口或者右键打开是乱码，有办法解决吗？

### ISSUE THREAD

**Issue by mayruiawo** [telppa/SciTE4AutoHotkey-Plus#45]
快捷方式拖入窗口或者右键打开是乱码，有办法解决吗？

**Comment by telppa** [comment]
快捷方式上右键，编辑脚本。直接拖入打开的是快捷方式本身。

**Comment by telppa** [comment]
> > 快捷方式上右键，编辑脚本。直接拖入打开的是快捷方式本身。
> > 我的右键没有编辑脚本的选项，是不是我安装时候哪弄错了

SciTE\tools\AHK 脚本关联工具\AHK 脚本关联工具.ahk

运行这个，设置好编辑器，就有了。
