### ISSUE TITLE
win10 64位安装失败，直接复制过去，没有办法运行

### ISSUE THREAD

**Issue by woaidianqian** [telppa/SciTE4AutoHotkey-Plus#7]
win10 64位安装失败，直接复制过去，没有办法运行，不知道为什么一定要管理员权限，做成绿色便携版多稳定，说明里面说直接复制文件夹过去就能用，事实上并不是。。。。

**Comment by telppa** [comment]
屏蔽字体安装相关代码是可以的，以前没有安装特别的字体，但是不安装又特别丑，所以后来强制安装了。
